name: Test and deploy
on:
  push:
    branches:
      - master
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      run: npm install
    - name: Run testcases
      run: npm test
    - name: Build and deploy
      uses: ./actions/deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
