name: Run health check
on:
  schedule:
  - cron: 0 0 * * *
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: docker://ianwalter/puppeteer:2.0.0
      with:
        args: npm install
    - name: Run health check
      uses: docker://ianwalter/puppeteer:2.0.0
      with:
        args: npm run test:health-check
    - name: Push health check
      uses: ./actions/push-health-check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
